# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Test' do
  pod 'AppCenter/Crashes', '~> 1.9.0'
  pod 'AppCenter/Analytics', '~> 1.9.0'
  pod 'AppCenterReactNativeShared', '~> 1.8.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Test

  

  platform :ios, '9.0'
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  target 'TestTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Test-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Test-tvOS

  target 'Test-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
